rootProject.name = 'gator-mail'
include 'keycloak-provider'

def gatorLibDir = file('../gator-lib')
if (!gatorLibDir.isDirectory()) { gatorLibDir = file('../javaProjects/gator-lib') }
if (gatorLibDir.isDirectory()) { includeBuild(gatorLibDir) }

def gatorWebGuiDir = file('../gator-lib-web-gui')
if (!gatorWebGuiDir.isDirectory()) { gatorWebGuiDir = file('../javaProjects/gator-lib-web-gui') }
if (gatorWebGuiDir.isDirectory()) { includeBuild(gatorWebGuiDir) }
